version: '3.8'

services:
  frontend:
    build: ./ecommerce-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./ecommerce-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/demo
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/demo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb

volumes:
  mongo-data:
